### ISSUE TITLE
[Question]: how does the sidecar (mesh worker role) intercept outbound traffic

### ISSUE THREAD

**Issue by sodaRyCN** [megaease/easegress#1127]
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

When the application call a rpc with domain name k8s-service.k8s-namespace , how does the sidecar (mesh worker role) intercept outbound traffic? 
eg: the application make a request to sidecar's port, or uses iptables?

**Comment by xxx7xxxx** [comment]
This document might have answered your question: https://github.com/megaease/easemesh/blob/main/docs/sidecar-protocol.md

**Comment by xxx7xxxx** [comment]
We create EaseMesh mainly for the spring cloud ecosystem. But we also maintain some other languages SDK[1]. You can use them to get part of the power of EaseMesh. And as for more general options like eBPF and IPTables are outside the scope of EaseMesh for the time being.

[1] https://github.com/megaease?q=easeagent-sdk&type=public&language=&sort=

**Comment by sodaRyCN** [comment]
> 本文档可能回答了您的问题：https://github.com/megaease/easemesh/blob/main/docs/sidecar-protocol.md

Thanks，very clear, but I still have some questions:

- `coredns will search service in easemesh etcd`，
   1）Is the easemesh's etcd instances in the same cluster as easegress's etcd?
   2）it means that no matter which domain name（targetServerA, targetServerB）the application uses to make RPC calls，the coredns always return the local sidecar address？
- `coredns return the local sidecar address`
   What I learned is that coredns will only return the IP but not the port, so how is the outbound traffic of the application forwarded to the 13002 port of the local sidecar?

**Comment by xxx7xxxx** [comment]
> 1）Is the easemesh's etcd instances in the same cluster as easegress's etcd?

yes

> 2）it means that no matter which domain name（targetServerA, targetServerB）the application uses to make RPC calls，the coredns always return the local sidecar address？

Nope, return the local sidecar address when only asking for existing mesh service names.

> What I learned is that coredns will only return the IP but not the port, so how is the outbound traffic of the application forwarded to the 13002 port of the local sidecar?

Actually CoreDNS returns ports, and we are maintaining our own CoreDNS version to get the dedicated job done.

**Comment by sodaRyCN** [comment]
I see. 
And I want to know, is it still only adding the target RPC server's name inside the HTTP header through easeagent to tell the local sidecar the real target service?

**Comment by xxx7xxxx** [comment]
> is it still only adding the target RPC server's name inside the HTTP header through easeagent to tell the local sidecar the real target service?

Yes, that's what the protocol specifies.

**Comment by sodaRyCN** [comment]
thanks for your replay
