### ISSUE TITLE
An option for enabling periodic health checks of the servers in Proxy plugin

### ISSUE THREAD

**Issue by zhao-kun** [megaease/easegress#1139]
**Is your feature request related to a problem? Please describe.**
We have several addresses of servers configured in the Proxy, and some servers may fail during the runtime. the Easegress should automatically orchestrate traffic into normal servers instead of abnormal servers.

**Describe the solution you'd like**
Nginx has a module [ngx_http_upstream_hc_module](https://nginx.org/en/docs/http/ngx_http_upstream_hc_module.html). Easegress can implement an option to enable periodic health checks.

**Describe alternatives you've considered**
No alternatives

**Additional context**

---
Thanks for contributing 🎉!

**Comment by suchen-sci** [comment]
Copy that!

**Comment by xxx7xxxx** [comment]
Fixed by https://github.com/megaease/easegress/pull/1143
