### ISSUE TITLE
[Question]: egctl apply error

### ISSUE THREAD

**Issue by cyrnicolase** [megaease/easegress#1161]
When I use ` egctl apply -f http-server.yml` to create a http server, I got an error .

```
Error: create HTTPServer http_server_proxy failed, Post "https://localhost:2381/apis/v2/objects": http: server gave HTTP response to HTTPS client
```

How do I get rid of the tls ?

**Comment by suchen-sci** [comment]
```
➜  easegress git:(main) ✗ curl -X POST --data-binary "@yamls/httpserver.yaml" http://localhost:2381/apis/v2/objects -v  
```
replace `yamls/httpserver.yaml` to your yaml. 

This is a really rare bug of `egctl` when create some special `HTTPServer` yaml that contains certain type of error. We will try to fix it tomorrow. For now, you can use the `curl` command above to create it, the response will contains the information. This bug will not influence the `easegress-server`.

Sorry for any inconvenience.

**Comment by cyrnicolase** [comment]
Thank you. It works!
