### ISSUE TITLE
[feature] Supporting a mockup filter

### ISSUE THREAD

**Issue by haoel** [megaease/easegress#152]
Sometimes, we need a fake HTTP API for mock tests.  This is a new requirement for a mock filter that can return the configured status code and response body.

**Comment by benja-wu** [comment]
Easegress has a filter called `mock` currently. here is its [spec](https://github.com/megaease/easegress/blob/main/doc/filters.md#mock)
It's capable to mock a desired HTTP status code and boy for one HTTP request. 
I will figure whether we need more complicated features in this filter.

**Comment by haoel** [comment]
I think that's totally fine.  sorry didn't notice that. I am going to close this issue.
