### ISSUE TITLE
Response appears 411 : MissingContentLength

### ISSUE THREAD

**Issue by zhongdonglin** [megaease/easegress#154]
I always return 411 when I make a PUT request. I don't know if it's a bug in the tool.

[2021-07-28T15:11:43.267+08:00] [192.168.0.115:48252 192.168.0.115 PUT /zlin1/temp.j2 HTTP/1.1 411] [1.00507014s rx:599B tx:457B] [proxy#main#addr: http://localhost:8001 | proxy#main#code: 411 | pipeline: proxy(4.063488ms) | proxy#main#duration: 1.004979489s]

**Comment by benja-wu** [comment]
> I always return 411 when I make a PUT request. I don't know if it's a bug in the tool.
> 
> [2021-07-28T15:11:43.267+08:00] [192.168.0.115:48252 192.168.0.115 PUT /zlin1/temp.j2 HTTP/1.1 411] [1.00507014s rx:599B tx:457B] [proxy#main#addr: http://localhost:8001 | proxy#main#code: 411 | pipeline: proxy(4.063488ms) | proxy#main#duration: 1.004979489s]

According to the log message you provided, it seems that your `localhost:8001` server responses `411` to Easegress' proxy filter. For confirming this behavior, I propose 
* Using `curl` or other HTTP related tool to visit your `localhost:8001` directly with the `PUT` request in your previous test. If this `411` result continues,  we can make use that Easegress didn't trigger this HTTP code.
* If this `411` response disappear, then I suggest you can provide more details such as the pipeline's YAML content, the HTTPServer's YAML, your temp.j2 and so on for helping us reproduce this problem. Thx

**Comment by zhongdonglin** [comment]
It is true that the 411 is generated when the easegress initiates the request. When I use another tool to put localhost:8001, it is 200.

Here is the configuration and file :

- HTTPServer's YAML

kind: HTTPServer
name: server-demo
port: 10080
keepAlive: true
https: false
rules:
  \- paths:
    \- pathPrefix: /
      backend: pipeline-demo

- pipeline's YAML

name: pipeline-demo
kind: HTTPPipeline
flow:
  \- filter: proxy
filters:
  \- name: proxy
    kind: Proxy
    mainPool:
      servers:
      \- url: http://localhost:8000
      \- url: http://localhost:8001
      loadBalance:
        policy: roundRobin

- temp.j2

test={% for i in range(0,4) %}
host{{i}}:{{i}}{% if not loop.last %},{% endif %}{% endfor %}

haha

**Comment by benja-wu** [comment]
@zhongdonglin 
Hmm, interestring..

* Did you `PUT` your `localhost: 8001/zlin1/temp.j2` with other tools? 
* And how can I run your temp.j2 in my environment, is `localhost:8001` a nodejs HTTP server or something else?

BTW: If you are running a unix liked env, perhaps using `sudo tcpdump -iany -s0 -X -n port 8001` for dumping the HTTP request from Easegress and your `localhost:8001` server can make this problem more clear.

**Comment by zhao-kun** [comment]
> It is true that the 411 is generated when the easegress initiates the request. When I use another tool to put localhost:8001, it is 200.
> 
> Here is the configuration and file :
> 
> * HTTPServer's YAML
>   ```yaml
>   kind: HTTPServer
>   name: server-demo
>   port: 10080
>   keepAlive: true
>   https: false
>   rules:
>     \- paths:
>       \- pathPrefix: /
>         backend: pipeline-demo
>   ```
> * pipeline's YAML
>   ```yaml
>   name: pipeline-demo
>   kind: HTTPPipeline
>   flow:
>     \- filter: proxy
>   filters:
>     \- name: proxy
>       kind: Proxy
>       mainPool:
>         servers:
>         \- url: http://localhost:8000
>         \- url: http://localhost:8001
>         loadBalance:
>           policy: roundRobin
>   ```
> * temp.j2
>   ```
>   test={% for i in range(0,4) %}
>   host{{i}}:{{i}}{% if not loop.last %},{% endif %}{% endfor %}
>   ```
> 
> haha

Can you tell us whats backend server (listened on 8000/8801) did you use?

**Comment by qdongxu** [comment]
> It is true that the 411 is generated when the easegress initiates the request. When I use another tool to put localhost:8001, it is 200.
> 
> Here is the configuration and file :
> 
> * HTTPServer's YAML
>   ```yaml
>   kind: HTTPServer
>   name: server-demo
>   port: 10080
>   keepAlive: true
>   https: false
>   rules:
>     \- paths:
>       \- pathPrefix: /
>         backend: pipeline-demo
>   ```
> * pipeline's YAML
>   ```yaml
>   name: pipeline-demo
>   kind: HTTPPipeline
>   flow:
>     \- filter: proxy
>   filters:
>     \- name: proxy
>       kind: Proxy
>       mainPool:
>         servers:
>         \- url: http://localhost:8000
>         \- url: http://localhost:8001
>         loadBalance:
>           policy: roundRobin
>   ```
> * temp.j2
>   ```
>   test={% for i in range(0,4) %}
>   host{{i}}:{{i}}{% if not loop.last %},{% endif %}{% endfor %}
>   ```
> 
> haha

Hi @zhongdonglin , Can you please paste a sample request and response if you test with a command-line tool. if you use a GUI tool for the test, welcome to join https://openmegaease.slack.com/archives/C028Z6SUCU9   for instant discussion, and past the screen snapshot in the `Slack channel`. This would be more efficient to make clear the cause. 😄

**Comment by zhongdonglin** [comment]
> > It is true that the 411 is generated when the easegress initiates the request. When I use another tool to put localhost:8001, it is 200.
> > Here is the configuration and file :
> > ...
> 
> Can you tell us whats backend server (listened on 8000/8801) did you use?

I'm using the Ceph cluster backend ,which is using Amazon's Amazon Simple Storage Service API (Amazon S3 REST API)

**Comment by zhongdonglin** [comment]
My request flow is as follows:

- Use python3 to send the Amazon Storage Service API
- Easegress receiving Agent
- Ceph Cluster Backend receives requests

When I proxy with Nginx instead of Easegress, the request is allowed to pass.However, when using Easegress, the 411 occurs.I wonder if it is because the Easegress has neglected something in the process of forwarding.

**Comment by zhao-kun** [comment]
> > > It is true that the 411 is generated when the easegress initiates the request. When I use another tool to put localhost:8001, it is 200.
> > > Here is the configuration and file :
> > > ...
> > 
> > 
> > Can you tell us whats backend server (listened on 8000/8801) did you use?
> 
> I'm using the Ceph cluster backend ,which is using Amazon's Amazon Simple Storage Service API (Amazon S3 REST API)

Got it, we will repdocue the issue in our environment

**Comment by zhao-kun** [comment]
> My request flow is as follows:
> 
> * Use python3 to send the Amazon Storage Service API
> * Easegress receiving Agent
> * Ceph Cluster Backend receives requests
> 
> When I proxy with Nginx instead of Easegress, the request is allowed to pass.However, when using Easegress, the 411 occurs.I wonder if it is because the Easegress has neglected something in the process of forwarding.

Thank you for provides this useful background information, we will reproduce the issue in our environment and dig into details of the root cause.

**Comment by zhao-kun** [comment]
One more question about the background, @zhongdonglin which version of the Ceph do you used in your environment? thx

**Comment by zhongdonglin** [comment]
> One more question about the background, @zhongdonglin which version of the Ceph do you used in your environment? thx

octopus (version 15). Thanks

**Comment by benja-wu** [comment]
@zhongdonglin, Thanks for providing more details.
And also welcome to join our Easegress community slack:  https://openmegaease.slack.com/archives/C028Z6SUCU9. 
:-)

**Comment by zhongdonglin** [comment]
I think I found the reason. The packet shows that my header has a transfer-encoding: chunked, resulting in no content-length.How can i  set and clear it?

**Comment by benja-wu** [comment]
> I think I found the reason. The packet shows that my header has a transfer-encoding: chunked, resulting in no content-length.How can i set and clear it?

* First of all, I would like to know, is this `transfer-encoding: chunked` is set by your Python S3 API? Can it be disabled by configuring this API when using? 
* Easegress has a filter called `requestAdaptor`, here is its [spec](https://github.com/megaease/easegress/blob/main/doc/filters.md#requestadaptor). You can use this filter before the proxy filter for modifying the request's header.

``` yaml
...
  kind: RequestAdaptor
  name: request-adaptor-example
  method: PUT
  header:
      set:
         conttent-lengh: 1024 
```
Although Easegress has a `text template` feature for support 
```yaml 
      set:
        valid : "[[filter.aggregatorOne.req.proto]]"
```
this feature, but currently it can only abstract the value from the filters before. And we don't have `[[filter.${filtername}.req.length]]` now. Maybe you can contribute a PR for this `.length` template replacing. :-) 

* If it confuses you, again, welcome to our slack for a more detailed discussion.

**Comment by zhongdonglin** [comment]
I have fixed the problem because the ContentLength in HTTP.Request was not written.

- net.http :
```
if body != nil {
    switch v := body.(type) {
    case *bytes.Buffer:
        req.ContentLength = int64(v.Len())
        buf := v.Bytes()
        req.GetBody = func() (io.ReadCloser, error) {
            r := bytes.NewReader(buf)
            return ioutil.NopCloser(r), nil
        }
    case *bytes.Reader:
        req.ContentLength = int64(v.Len())
        snapshot := *v
        req.GetBody = func() (io.ReadCloser, error) {
            r := snapshot
            return ioutil.NopCloser(&r), nil
        }
    case *strings.Reader:
        req.ContentLength = int64(v.Len())
        snapshot := *v
        req.GetBody = func() (io.ReadCloser, error) {
            r := snapshot
            return ioutil.NopCloser(&r), nil
        }
    default:
    }
    if req.GetBody != nil && req.ContentLength == 0 {
        req.Body = NoBody
        req.GetBody = func() (io.ReadCloser, error) { return NoBody, nil }
    }
}
```

The newRequest method should include an assignment of content.length.Modify the following
```
func (p *pool) newRequest(ctx context.HTTPContext, server *Server, reqBody io.Reader) (*request, error) {
	req := &request{
		createTime: time.Now(),
		server:     server,
		statResult: &httpstat.Result{},
	}

	r := ctx.Request()

	url := server.URL + r.Path()
	if r.Query() != "" {
		url += "?" + r.Query()
	}

	newCtx := httpstat.WithHTTPStat(ctx, req.statResult)
	stdr, err := http.NewRequestWithContext(newCtx, r.Method(), url, reqBody)
	if err != nil {
		return nil, fmt.Errorf("BUG: new request failed: %v", err)
	}

	stdr.Header = r.Header().Std()
	stdr.Host = r.Host()
        var length []string = stdr.Header["Content-Length"]
        if len(length) != 0 {
    	    for _, n := range length{
                int64, err := strconv.ParseInt(n, 10, 64)
                stdr.ContentLength = int64
                if err != nil {
                    fmt.Printf("err : %v ", err)
                }
            }
        }

	req.std = stdr

	return req, nil
}
```

**Comment by localvar** [comment]
Thanks @zhongdonglin , could you please create a PR for the change?
