### ISSUE TITLE
Improve coverage

### ISSUE THREAD

**Issue by phanirithvij** [megaease/easegress#158]
The code coverage https://app.codecov.io/gh/megaease/easegress seems to be less than 60%.

It would be great if it can be brought up around 80-90% and ideally a 100%.

**Comment by benja-wu** [comment]
Hi, @phanirithvij. Thanks for the suggestion. 
Yes, I am totally agreed with you. And We are working on raising the coverage rate aiming at 85% at least. 
And we are also opened to any kind of suggestions and contributions. If u are interested in Easegress project, welcome to join our Easegress product slack: https://openmegaease.slack.com/archives/C028Z6SUCU9,  as well. :-)

**Comment by benja-wu** [comment]
HI， @phanirithvij  
we,@localvar @suchen-sci , had added some test cases, and now the coverage rate is 81%.
https://app.codecov.io/gh/megaease/easegress
I closed this issue but we will continue to work on it.
