### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by zhongdonglin** [megaease/easegress#160]
This error occurs when I use mirrorPool.Because `func (mr *masterReader) Read(p []byte) (n int, err error)` repeats the Clone method twice.
I have made some changes to this for reference only：
```
func (mr *masterReader) Read(p []byte) (n int, err error) {
        buff := bytes.NewBuffer(nil)
        tee := io.TeeReader(mr.r, buff)
        n, err = tee.Read(p)

        if n != 0 {
                mr.buffChan <- buff.Bytes()
        } else {
                close(mr.buffChan)
        }

        // if err == io.EOF {
                // close(mr.buffChan)
        // }

        return n, err
}
```

**Comment by benja-wu** [comment]
hi @zhongdonglin, thanks for reporting. 
Can u share the panic stack and how to reproduce this panic? It's better for providing more details such as reproducing steps, Easegress YAML, and so on for problem/bug reporting. :-)

**Comment by zhao-kun** [comment]
@zhongdonglin you paste a piece of code that is changed by you, it can't help us diagnose the issue. Could you provide us the stack trace information of panic produced by the original code? Other background included(but not limited to), like Yaml spec etc. It will be better to help us solve the issue.

**Comment by benja-wu** [comment]
Closing, not enough information, please reopen if the needed information is provided.
