### ISSUE TITLE
Why did close client and peers manually

### ISSUE THREAD

**Issue by jxd134** [megaease/easegress#172]
https://github.com/megaease/easegress/blob/e0bdd3f0a76ede3cd6ef6ef7b714af60dd28383d/pkg/cluster/cluster.go#L614

T think ectd clients and peers is already closed in *embed.Etcd.Close(), there is no need to close it again.

**Comment by xxx7xxxx** [comment]
Thx for your careful review, your opinion is right even it seems repeatedly close for it won't cause errors, we will refine it.

**Comment by jxd134** [comment]
> 
> 
> Thx for your careful review, your opinion is right even it seems repeatedly close for it won't cause errors, we will refine it.

nice

**Comment by benja-wu** [comment]
@jxd134 Thx for reminding.

In usual, 
``` golang
...
case <-s.Server.ReadyNotify():
		s.Close()
...
```

This branch will cover this shutdown logic completely. But if we enter `HardStop` logic, I think we should close these `clients` and `peers` manually since the `HardStop` in embed.Etcd only sends a signal to [quit the `run` function as [here](https://github.com/etcd-io/etcd/blob/1e46145b29764f9e65f4164bb777fbf275a63d8a/server/etcdserver/server.go#L1187). 


So I prefer to refine it like this:

``` golang
unc closeEtcdServer(s *embed.Etcd) {
	select {
	case <-s.Server.ReadyNotify():
		s.Close()
		<-s.Server.StopNotify()
	default:
		s.Server.HardStop()
		for _, client := range s.Clients {
			if client != nil {
				client.Close()
			}
		}
		for _, peer := range s.Peers {
			if peer != nil {
				peer.Close()
			}
		}
		logger.Infof("hard stop server")
	}
}
```
Any further suggestions?

**Comment by jxd134** [comment]
> 
> 
> @jxd134 Thx for reminding.
> 
> In usual,
> 
> ```go
> ...
> case <-s.Server.ReadyNotify():
> 	s.Close()
> ...
> ```
> 
> This branch will cover this shutdown logic completely. But if we enter `HardStop` logic, I think we should close these `clients` and `peers` manually since the `HardStop` in embed.Etcd only sends a signal to quit the `run` function as [here](https://github.com/etcd-io/etcd/blob/1e46145b29764f9e65f4164bb777fbf275a63d8a/server/etcdserver/server.go#L1187).
> 
> So I prefer to refine it like this:
> 
> ```go
> func closeEtcdServer(s *embed.Etcd) {
> 	select {
> 	case <-s.Server.ReadyNotify():
> 		s.Close()
> 		<-s.Server.StopNotify()
> 	default:
> 		s.Server.HardStop()
> 		for _, client := range s.Clients {
> 			if client != nil {
> 				client.Close()
> 			}
> 		}
> 		for _, peer := range s.Peers {
> 			if peer != nil {
> 				peer.Close()
> 			}
> 		}
> 		logger.Infof("hard stop server")
> 	}
> }
> ```
> 
> Any further suggestions?

Yes.
I agree with you.
The clients and peers doesn't close in `s.Server.HardStop()`, so it need to be closed in default block.
