### ISSUE TITLE
[question] have any suggestions for the deployment of high-availability mode?

### ISSUE THREAD

**Issue by brzyangg** [megaease/easegress#195]
I want to deploy a easegress cluster with multiple members. 
Have any suggestions for the deployment of high-availability mode?
PS：I want to deploy many members, will there be some problems with raft?

**Comment by localvar** [comment]
Easegress embed ETCD to store configuration, and an Easegress member can be one of two roles (specified by the `cluster-role` option)s:

* Writer: a member of the ETCD cluster, will create a built-in ETCD service
* Reader: from the view of ETCD, it is a client.

As [recommended by ETCD](https://etcd.io/docs/v2.3/admin_guide/#optimal-cluster-size):
> The recommended etcd cluster size is 3, 5 or 7, which is decided by the fault tolerance requirement. A 7-member cluster can provide enough fault tolerance in most cases. While larger cluster provides better fault tolerance the write performance reduces since data needs to be replicated to more machines

We suggest deploy 3, 5 or 7 of Easegress members as `Writer`.

**Comment by brzyangg** [comment]
thank you
