### ISSUE TITLE
TCP Proxy Support?

### ISSUE THREAD

**Issue by siaron** [megaease/easegress#201]
I see the supported application layer protocol proxy. So does TCP support? There are scenarios based on Netty's TCP persistent connection applications. IoT scenarios.

**Comment by benja-wu** [comment]
Hi @siaron 
Currecntly，Easegress is an L7 traffic orchestration system. 
* **It doesn't  TCP proxying right now**. However, as being a modern traffic orchestration system, I believe it should be TCP supported in the future. 

* We are working on support `MQTT proxy`. And `WebSocket proxy` supporting had been done. `MQTT proxy` is aiming for IoT scenarios too, if u are also interested, feel free to join in our design issue #187. 

* **quick brainstorm** I think `TCP supporting` should be implemented into the `TrafficController` of Easegress. Then the whole raw TCP connections can be managed in one place, so the `WebSocket proxy` and `MQTT proxy` can benefit from this low-level feature too.

**Comment by benja-wu** [comment]
Since we had open a design discussion issue #229 for this topic, let me close this question issue.
Welcome to join us in #229 .
