### ISSUE TITLE
can not build easegress cluster

### ISSUE THREAD

**Issue by jxd134** [megaease/easegress#207]
```bash
sudo ./server --api-addr 192.168.42.103:38080 \
--cluster-listen-client-urls  http://192.168.42.103:2379 \
--cluster-listen-peer-urls http://192.168.42.103:2380 \
--cluster-advertise-client-urls http://192.168.42.103:2379 \
--cluster-initial-advertise-peer-urls http://192.168.42.103:2380 \
--cluster-join-urls http://192.168.42.104:2380,http://192.168.42.103:2380,http://192.168.42.105:2380 \
--cluster-name gw-cluster --force-new-cluster false --cluster-role writer --name gw1 

sudo ./server --api-addr 192.168.42.104:38080 \
--cluster-listen-client-urls  http://192.168.42.104:2379 \
--cluster-listen-peer-urls http://192.168.42.104:2380 \
--cluster-advertise-client-urls http://192.168.42.104:2379 \
--cluster-initial-advertise-peer-urls http://192.168.42.104:2380 \
--cluster-join-urls http://192.168.42.105:2380,http://192.168.42.103:2380,http://192.168.42.104:2380 \
--force-new-cluster false --cluster-name gw-cluster --cluster-role writer --name gw2 

sudo ./server --api-addr 192.168.42.105:38080 \
--cluster-listen-client-urls  http://192.168.42.105:2379 \
--cluster-listen-peer-urls http://192.168.42.105:2380 \
--cluster-advertise-client-urls http://192.168.42.105:2379 \
--cluster-initial-advertise-peer-urls http://192.168.42.105:2380 \
--cluster-join-urls http://192.168.42.103:2380,http://192.168.42.105:2380,http://192.168.42.104:2380 \
--force-new-cluster false --cluster-name gw-cluster --cluster-role writer --name gw3 
```

I run above command  on three nodes. 

![图片](https://user-images.githubusercontent.com/14814212/130601686-551dd755-65fa-4626-a9b5-49b84e3f78ea.png)

Above is the easegress running result.

I have create a http server like this:

![图片](https://user-images.githubusercontent.com/14814212/130601780-06059696-02f8-428e-9aec-01b6373c07c5.png)

But easegress just start a http server on node(192.168.42.103), didn't create http server on node(42.104/42.105).
T think when i create a http server on node(42.103), the easegree-cluster should create http server on node(42.104/105) by object watcher notify.

And i find that each node etcd state is leader. I think etcd-cluster can only have one leader.

![图片](https://user-images.githubusercontent.com/14814212/130602046-6d7399f6-e77b-443c-9d7f-319bdd026096.png)
![图片](https://user-images.githubusercontent.com/14814212/130602094-87fa0f4e-2702-433a-9e31-61c8829e3407.png)

**Comment by benja-wu** [comment]
Hi, @jxd134 
I think the problem is due to these configurations
``` yaml
...
--cluster-join-urls http://192.168.42.104:2380,http://192.168.42.103:2380,http://192.168.42.105:2380 
...
--cluster-join-urls http://192.168.42.105:2380,http://192.168.42.103:2380,http://192.168.42.104:2380 \

....

--cluster-join-urls http://192.168.42.103:2380,http://192.168.42.105:2380,http://192.168.42.104:2380 \
...

```
If these three nodes want to form a cluster, then the `--cluster-join-urls` should be the same.
* EG will use this `cluster-join-urls` for trying to join the cluster.
* If the first node of `cluster-join-urls` is itself, then it will skip this join routine, and waiting for other nodes' join.
* You can notice this requirement from Easegress' `example` dir's cluster configurations.

**Comment by jxd134** [comment]
```bash
sudo ./server --api-addr 192.168.42.103:38080 \
--cluster-listen-client-urls  http://192.168.42.103:2379 \
--cluster-listen-peer-urls http://192.168.42.103:2380 \
--cluster-advertise-client-urls http://192.168.42.103:2379 \
--cluster-initial-advertise-peer-urls http://192.168.42.103:2380 \
--cluster-join-urls http://192.168.42.103:2380,http://192.168.42.104:2380,http://192.168.42.105:2380 \
--cluster-name gw-cluster --force-new-cluster false --cluster-role writer --name gw1 \

sudo ./server --api-addr 192.168.42.104:38080 \
--cluster-listen-client-urls  http://192.168.42.104:2379 \
--cluster-listen-peer-urls http://192.168.42.104:2380 \
--cluster-advertise-client-urls http://192.168.42.104:2379 \
--cluster-initial-advertise-peer-urls http://192.168.42.104:2380 \
--cluster-join-urls http://192.168.42.103:2380,http://192.168.42.104:2380,http://192.168.42.105:2380 \
--force-new-cluster false --cluster-name gw-cluster --cluster-role writer --name gw2 \

sudo ./server --api-addr 192.168.42.105:38080 \
--cluster-listen-client-urls  http://192.168.42.105:2379 \
--cluster-listen-peer-urls http://192.168.42.105:2380 \
--cluster-advertise-client-urls http://192.168.42.105:2379 \
--cluster-initial-advertise-peer-urls http://192.168.42.105:2380 \
--cluster-join-urls http://192.168.42.103:2380,http://192.168.42.104:2380,http://192.168.42.105:2380 \
--force-new-cluster false --cluster-name gw-cluster --cluster-role writer --name gw3 \
```

@benja-wu Thanks for your explian. I have change the configuration and first start node(42.103).
But there still some porblem as i mentioned above.

![图片](https://user-images.githubusercontent.com/14814212/130605205-06d6ba85-84c1-468e-ae74-68a663132bc3.png)
![图片](https://user-images.githubusercontent.com/14814212/130605252-2cb7bb8d-4cde-4278-800e-95be4fbf8daa.png)

I can't run clsuter-example on my ubuntu server, may be i can fix in this week.

**Comment by benja-wu** [comment]
Emm.... strange
https://openmegaease.slack.com/?redir=%2Farchives%2FC028Z6SUCU9 this is our Easegress product slack, can u join and provide us more details? I would like to know more details and information about this problem. Thx.

**Comment by jxd134** [comment]
@benja-wu I'm glad to join the slack.
But i didn't know how to join the openmegease slack.

**Comment by benja-wu** [comment]
Click this https://openmegaease.slack.com/?redir=%2Farchives%2FC028Z6SUCU9  URL, and register with your Gmail, then your browser will redirect to slack APP and open the work space. :-)

**Comment by jxd134** [comment]
@benja-wu 
![图片](https://user-images.githubusercontent.com/14814212/130610803-f3ad9644-a72e-4090-a3f9-7b647ad200e4.png)
This is the log for node(42.103).

![图片](https://user-images.githubusercontent.com/14814212/130611005-fce4ab81-d729-4916-b92d-dbdf2cb7be83.png)
And this is the log for node(42.104).

Before execute the easegress server, i have clean the previous file, just left the server.

**Comment by benja-wu** [comment]
* Your email account had been added into slack now. :-) 
* I think the root cause is here, in `config.go`, 
``` golang
			if c.members.clusterMembersLen() == 1 &&
				common.IsDirEmpty(c.opt.AbsDataDir) {
				ec.ClusterState = embed.ClusterStateFlagNew
			}
```
The first time standalone clusters store their staus into the local `member.yaml` file, then next time, the instance will read this file firstly, then it can only recognize itself in their cluster, that will the embedded Etcd's initial status is `new`.

**Comment by benja-wu** [comment]
After communicating in slack and changing to use the starting command as
``` bash
√ writer-001 $ ./bin/easegress-server --cluster-join-urls=http://127.0.0.1:12380, http://127.0.0.1:22380, http://127.0.0.1:32380 --cluster-name=cluster-test --name=writer-001 --cluster-role=writer --cluster-listen-client-urls=http://127.0.0.1:12379 --cluster-advertise-client-urls=http://127.0.0.1:12379 --cluster-listen-peer-urls=http://127.0.0.1:12380 --api-addr=127.0.0.1:12381 --cluster-initial-advertise-peer-urls=http://127.0.0.1:12380
```
* We finally get a health Easegress cluster in @jxd134 's environment. 
* Currently, Easegress' cluster start-up routine is a bit different from the original Etcd's. We need to open a new issue for reviewing and discussing whether we should stick to this design or roll back to use the original Etcd's.
