### ISSUE TITLE
The gateway service returns errorCode when there is an error, but I want to return a json structure. How can I do that? Such as {" message ":" MSG ", "result" : ""}

### ISSUE THREAD

**Issue by llooper-dev** [megaease/easegress#209]
The gateway service returns errorCode when there is an error, but I want to return a json structure. How can I do that?
Such as {" message ":" MSG ", "result" : ""}

**Comment by llooper-dev** [comment]
我想成功或失败都返回json结构，怎么实现呢？

**Comment by localvar** [comment]
hi @llooper-dev , could you please provide more detais about the question?
for example: what have you done before you see the error, and for `The gateway service returns errorCode`, are you modify the source code? or after you send a command to easegress server?

**Comment by localvar** [comment]
close as no update for more than 10 days. please feel free to re-open it if it still exists.

**Comment by localvar** [comment]
close as the issue is not clearly described and is staled for more than a year.
BTW: Easegress is now able to return error messages in JSON.
