### ISSUE TITLE
Provide Helm Chart Please

### ISSUE THREAD

**Issue by 4bo** [megaease/easegress#237]
hello all
as Helm Charts is a typical way to manage k8s resources, please add a helm chart and register it in https://artifacthub.io/.
this will enable more poeple to use easegress.

**Comment by benja-wu** [comment]
Hi @4bo 

* Thanks for the reminder!  Let me figure out how to add this helm chart first. :-)

**Comment by 4bo** [comment]
thank you @benja-wu 
also, providing a sample/reference declarative manifest would be helpful.
currently, in the docs almost all resources are created with ```egctl```, which is not compatible with Infrastructure as code.

**Comment by localvar** [comment]
hello @4bo , now we have added helm charts for both ingress controller and normal Easegress installation, please help confirm this meets your requirement and close the issue, thanks.

**Comment by samutamm** [comment]
https://github.com/megaease/easegress/pull/395 and https://github.com/megaease/easegress/pull/444 should resolve this issue. Closing as done, please be free to re-open if needed.
