### ISSUE TITLE
[document] add comparisons section for better understanding and choose

### ISSUE THREAD

**Issue by feitian124** [megaease/easegress#259]
thank you for open source this great project.
can we add a comparisons section in document so new comer like me can get a better understanding of its pros and cons?
like comparisons with below:

- [apisix](https://github.com/apache/apisix) The Cloud-Native API Gateway 
- [traefik](https://github.com/traefik/traefik) The Cloud Native Application Proxy 
- [spring-cloud-gateway](https://github.com/spring-cloud/spring-cloud-gateway)

i used some of above, maybe also kong, tyk etc.

**Comment by benja-wu** [comment]
Hi @feitian124, I think this is a good suggestion for Easegress. 
We will work on it later. Thx

**Comment by jxd134** [comment]
I agree with it.
The comparison is not limited to performance, but also function, design.

**Comment by feitian124** [comment]
:+1: thank you for quick response
