### ISSUE TITLE
How to make cluster arch architect

### ISSUE THREAD

**Issue by Liubey** [megaease/easegress#260]
Just confused,
easegress has a Leader node？Is traffic all through the leader and forward to other node? I mean ,how to load balance the traffic? Is nginx/vip or something at front of easegress?
thank you.

**Comment by zhao-kun** [comment]
Easegress's leader and follower is the role of the Easegress control plane, which manages metadata of the Easegress controllers, and pipeline/filters configuration. It has no relationship with the Easegress data plane, but a node with a leader or follower role can still accept HTTP traffic.

I hope that my explains can eliminate the confusion of yours

**Comment by Liubey** [comment]
thank you for your answer,now I know the control plane/data plane definition in Easegress.
but just also don't get it about how to build a cluster of data plane,need nginx/lvs ？
traffic -->nginx/lvs --->load balance to every Easegress data plane?

**Comment by benja-wu** [comment]
@Liubey 
* Management traffic is all through the leader. 
* Real business traffic can run through all Easegress instances. 
* For example, if u create an HTTPServer in the Easegress cluster which listens 10080 port, then all instances inside the Easegress cluster will create an HTTPServer for receiving 10080 port traffic. So I think the path should be

``` bash
user-> Traffic gateway(F5) -> API gateway (Easegress )
```

**Comment by zhao-kun** [comment]
I think a Layer three Loadbalance(LVS, F5) is the better choice for the data plane.

**Comment by haoel** [comment]
> but just also don't get it about how to build a cluster of data plane,need nginx/lvs ？
> 
> traffic -->nginx/lvs --->load balance to every Easegress data plane?

As same as how you've done for multiple nginx servers.

And the major purpose of Easegress cluster is for metadata consistency.

Hope this make senses to you.

-- Hao

**Comment by Liubey** [comment]
> @Liubey
> 
> * Management traffic is all through the leader.
> * Real business traffic can run through all Easegress instances.
> * For example, if u create an HTTPServer in the Easegress cluster which listens 10080 port, then all instances inside the Easegress cluster will create an HTTPServer for receiving 10080 port traffic. So I think the path should be
> 
> ```shell
> user-> Traffic gateway(F5) -> API gateway (Easegress )
> ```

wow,now I'm clear about. leader, it's for "management traffic" to make metadata consistency.

**Comment by Liubey** [comment]
@haoel @zhao-kun @benja-wu 
Thank you for your detailed answers.I'm very honored and clear about that.
