### ISSUE TITLE
WebAssembly Golang SDK

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#279]
As WebAssembly support and [AssemblyScript SDK](https://github.com/megaease/easegress-assemblyscript-sdk) are ready, Easegress needs to provide SDKs for more languages.

This issue tracks the progress of the Golang SDK, but the SDK source code should be put in a separate repository.

Because the official Go compiler generates too big binaries, the target compiler of the Golang SDK is [TinyGo](https://tinygo.org/), which was designed for embedded systems and WebAssembly.

Same as the AssemblyScript SDK, the Golang SDK need to wrap all host functions for the WebAssembly program, and exports required WebAssembly functions to host.

**Comment by xmh19936688** [comment]
I'd like to have a try.

**Comment by haoel** [comment]
> I'd like to have a try.

You can draft a WIP pull request to claim the ownership of this task. 😎
