### ISSUE TITLE
Pass in an empty object, the request will return MissingContentLength.

### ISSUE THREAD

**Issue by zhongdonglin** [megaease/easegress#282]
I use CEPH S3 interface. When I pass in an empty object, the request will return MissingContentLength. I looked at the net/ HTTP code because your request.Body is not nil.But my request actually arrives at Easegress is nil.
Below is the code for the NET/HTTP library:

```go
func (r *Request) outgoingLength() int64 {
	if r.Body == nil || r.Body == NoBody {
		return 0
	}
	if r.ContentLength != 0 {
		return r.ContentLength
	}
	return -1
}
```

Before I go to Easegress, my Body is nil, but because it goes through easegress, an address is written to the Body.So it returns a -1.
then:

```go
		t.ContentLength = rr.outgoingLength()
		if t.ContentLength < 0 && len(t.TransferEncoding) == 0 && t.shouldSendChunkedRequestBody() {
			t.TransferEncoding = []string{"chunked"}
		}
		// If there's a body, conservatively flush the headers
		// to any bufio.Writer we're writing to, just in case
		// the server needs the headers early, before we copy
		// the body and possibly block. We make an exception
		// for the common standard library in-memory types,
		// though, to avoid unnecessary TCP packets on the
		// wire. (Issue 22088.)
		if t.ContentLength != 0 && !isKnownInMemoryReader(t.Body) {
			t.FlushHeaders = true
		}
```

So I want to know, why do you have to rewrite Body in your code.Thanks.

**Comment by localvar** [comment]
Is it a new issue or does it related to #154 ?
Could you please provide the configuration?

**Comment by localvar** [comment]
close as the issue is staled for one year.
