### ISSUE TITLE
Any plan to add a dashboard UI like apisix-dashboard?

### ISSUE THREAD

**Issue by JackLeeHal** [megaease/easegress#285]
Is there any plan to add a dashboard UI like https://github.com/apache/apisix-dashboard?

**Comment by localvar** [comment]
This is a feature of the enterprise edition, which is not open-sourced.

**Comment by JackLeeHal** [comment]
> This is a feature of the enterprise edition, which is not open-sourced.

Cool, thanks for you reply.
