### ISSUE TITLE
Group configurations by a single Yaml file

### ISSUE THREAD

**Issue by zhao-kun** [megaease/easegress#29]
Many applications require multiple configurations to be created, such as an `HttpServer` and a `PipelineFilter`. Management of multiple configurations that grouped together in a single file (separated by --- in YAML) will bring huge simplicity to users.
like Kubernetes [1]

[1] https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/

**Comment by benja-wu** [comment]
I agree this feature can bring huge simplicity for Easegress CLI users. Since we are dealing with manage API framework replacement, I will implement this feature as soon as the replacement completed.
