### ISSUE TITLE
API access log need to be extended to include the header info at least

### ISSUE THREAD

**Issue by mydoors88** [megaease/easegress#301]
**Is your feature request related to a problem? Please describe.**
Need the header of each api request to get some useful information with the header flags
**Describe the solution you'd like**
Exetend the log format with the header  of each request

**Additional context**
please refer to the aliyun api gateway log setting to provide the solution.i.e. we can customized the log format.
https://www.alibabacloud.com/help/zh/doc-detail/64818.htm

**Comment by haoel** [comment]
thanks for raising this requirement, we will consider this feature later.
