### ISSUE TITLE
Pipeline support multiple protocols

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#315]
# Background

Easegress leverages pipeline for traffic orchestration, but the current pipeline implementation only supports HTTP protocol.
Although we have added the support of other protocols like MQTT, TCP/UDP with a workaround solution, it is very hard(if not impossible) to reuse filters originally designed for the HTTP protocol in these protocols.

# Objective

Redesign/refactor the existing pipeline implementation, make it possible to support other protocols, and make it possible to reuse one type of filter in different protocols.

**Comment by suchen-sci** [comment]
#352 MQTT Pipeline Develop Guide #352 contain information about MQTT pipeline and filter development. Include example yaml.
