### ISSUE TITLE
How to route a request from one easegress to another easegress

### ISSUE THREAD

**Issue by qqeasonchen** [megaease/easegress#380]
Suppose i use easegress as gateway, i want to route a request from one easegress to another easegress, is there a instruction? thanks.

**Comment by haoel** [comment]
Could you please describe the X problem we need to solve?   (refer to [X-Y problem](https://xyproblem.info/) )

**Comment by qqeasonchen** [comment]
> Could you please describe the X problem we need to solve?   (refer to [X-Y problem](https://xyproblem.info/) )

I just noticed that EaseMesh uses "one jump" and client mesh discovery, So ignore my question, Thanks for yout reply :)
