### ISSUE TITLE
Config the easegress with the enviroment variable in

### ISSUE THREAD

**Issue by mydoors88** [megaease/easegress#384]
**Is your feature request related to a problem? Please describe.**
configure the easegress with env setting and integrating with devops 
**Describe the solution you'd like**
as per the K8S environment variable usage, to enhance the yaml with environment variable 

**Additional context**
please refer to below link:
https://kubernetes.io/zh/docs/tasks/inject-data-application/define-environment-variable-container/

**Comment by suchen-sci** [comment]
#1072 added this feature.
