### ISSUE TITLE
Make system controller configurable

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#397]
In pr #391 , we have added a new controller named `AutoCertManager`, this controller handles certificates renewal for all HTTP servers which enables automated certificate management.

From the above fact, there should be at most one instance of the controller, and the controller should be a system controller instead of a business controller.

But currently, system controllers can only be configured by code, while the `AutoCertManager` needs to support dynamic configuration. 
As a workaround, the `AutoCertManager` was implemented as a business controller, but this leads to several issues, including: if a user creates two more instances of `AutoCertManager`, only a random instance is live.

To fix these issues, we need to make the system controllers support dynamic configuration and convert the `AutoCertManager` to a system controller.

**Comment by xxx7xxxx** [comment]
https://github.com/megaease/easegress/pull/1144 Fixed it.
