### ISSUE TITLE
can use easegress to build high-availability kubernetes？

### ISSUE THREAD

**Issue by gf-wangxu** [megaease/easegress#434]
if yes, how to do it?

**Comment by localvar** [comment]
we have helm charts for k8s deployment, please refer: https://github.com/megaease/easegress/tree/main/helm-charts/easegress

**Comment by gf-wangxu** [comment]
> we have helm charts for k8s deployment, please refer: https://github.com/megaease/easegress/tree/main/helm-charts/easegress

I want to build high-availability kubernetes, with like keepalive & haproxy. can easegress replace haproxy?

**Comment by localvar** [comment]
I don't think Easegress is a replacement for haproxy, Easegress could do load balance, but it is focusing on traffic orchestration.
