### ISSUE TITLE
run easegress-server -c command is error

### ISSUE THREAD

**Issue by martinou** [megaease/easegress#437]
**Describe the bug**
Print the configuration.but yet start server

**To Reproduce**
1. Execute 'run easegress-server -c'
2. Send a request to 'no send request'
3. See error
![1640251062(1)](https://user-images.githubusercontent.com/1960234/147218009-7506dd4c-f712-4162-9941-fb4236a06f58.png)

**Expected behavior**
print config

**Version**
1.4.0

**Configuration**
* Easegress Configuration
```yaml
```

* HTTP server configuration
```yaml
```

* Pipeline Configuration
```yaml
```

**Logs**
```
Easegress logs, if applicable.
```

**OS and Hardware**
 - OS: [e.g. Ubuntu 20.04]
 - CPU:[e.g. Intel(R) Core(TM) i5-8265U]
 - Memory: [e.g. 16GB]

**Additional context**

**Comment by martinou** [comment]
![1640251118(1)](https://user-images.githubusercontent.com/1960234/147218154-ad21fb6d-4ebb-49db-9a10-fe7e3a45c046.png)

**Comment by samutamm** [comment]
Currently `easegress-server` flag `-c` or `--print-config` prints the configuration AND starts the server. However when running `easegress-server --help`, `--print-config` has following description: `Print the configuration.` The description could also mention that the command will also start the server.

This is a  minor documentation improvement and you are very welcome to make PR to fix it.

On the other hand, if you already have the server running and you intent is to print the config, you can use the `egctl` CLI tool: run `egctl object list` to see all configured objects, which together form the configuration.
