### ISSUE TITLE
General Pipeline Design

### ISSUE THREAD

**Issue by suchen-sci** [megaease/easegress#466]
## What we want: 
We want:
1. `Pipeline` can create pipelines for different protocols, like HTTP, MQTT, TCP etc.  
    ```
    name: mqtt-pipeline
    kind: Pipeline
    protocol: MQTT
    ...
    ```

    ```
    name: http-pipeline
    kind: Pipeline
    protocol: HTTP
    ...
    ```

2. `http-pipeline` can be easily used by `HTTPServer` just like `HTTPPipeline` without change. `mqtt-pipeline` can be easily used by `MQTTProxy`.
3. `Pipeline` and `HTTPPipeline` is compatible with each other. Which means: 
    ```
    name: http-pipeline
    kind: Pipeline
    protocol: HTTP
    flow: ...
    filters: ...
    ```
    ```
    name: http-pipeline-demo
    kind: HTTPPipeline
    flow: ...
    filters: ...
    ```
    `Pipeline` `http-pipeline` and `HTTPPipeline` `http-pipeline-demo` should be equal. 

### Phase One

Now `HTTPServer` and `HTTPPipeline` are system controller and managed by `TrafficController` (under `RawConfigTrafficController`). 
But `Pipeline` and `MQTTProxy` are business controller and managed by `Supervisor` directly. To allow `HTTPServer` call `Pipeline`, 
we need to update `MQTTProxy` and `Pipeline` to system controller. 

TODO:
1. update `TrafficController` and related objects to support multiple protocols.
2. update `MQTTProxy` and `Pipeline` to system controller. 

### Phase Two

Make `Pipeline`, `HTTPPipeline` use same interface and same input structure. Now their interface is quite similar but a little different in detail. 
Then we will update all HTTP filters and registry them to both `Pipeline` and `HTTPPipeline`. 

TODO:
1. update `Spec`, `FilterSpec`, `Filter` interface to be compatible both for `Pipeline` and `HTTPPipeline`. 
2. update all HTTP filters to use new `FilterSpec` (very small change here, may only import `FilterSpec` from different file). 

To make things simple, when call `Pipeline` with protocol HTTP, `Pipeline` will create a `HTTPPipeline`. `HTTPPipeline` use chain of responsibility to 
call filters. We may copy all these functions from `HTTPPipeline` to `Pipeline` later. 

### Phase Three 

By now, the statuses of `HTTPServer` and `HTTPPipeline` are managed by `TrafficController` (all system controller status managed by `TrafficController`). After Phase One and Phase Two, 
`TrafficController` will also manage statuses of `MQTTProxy` and `Pipeline`. We will update this, the status of system controller 
will directly stored into etcd. Update to `egctl object status get` is also necessary.

## Test 

To test all these changes, unit test is not enough. We will add more integration test to make sure
Easegress still can create, update and delete `HTTPPipeline`, `HTTPServer`, `Pipeline` and `MQTTProxy`, `TCPProxy` etc.

**Comment by samutamm** [comment]
The design looks good in high level. I would like see slightly more detailed drafts for some of intermediate steps, like the first step in _Phase One_:

Currently `TrafficController` has functions

- `CreateHTTPPipeline(namespace string, entity *supervisor.ObjectEntity)`
- `CreateHTTPServer(namespace string, entity *supervisor.ObjectEntity)`
- `ApplyHTTPServer(namespace string, entity *supervisor.ObjectEntity)`
- `ApplyHTTPPipelineForSpec(namespace string, superSpec *supervisor.Spec)`

When `TrafficController` is updated to support other protocols (MQTT for example) in _Phase One_ , do you modify these signatures to more general `CreateServer` and `CreatePipelineForSpec`? Or will there be additional functions for each protocol, like `CreateMQTTPipeline(namespace string, entity *supervisor.ObjectEntity)` etc...?

**Comment by suchen-sci** [comment]
Thanks for your question, it will be: 
- `CreatePipeline(namespace string, protocol context.Protocol, entity *supervisor.ObjectEntity)`
- `CreateServer(namespace string, protocol context.Protocol, entity *supervisor.ObjectEntity)`

and it will call
- `processCreate(namespace string, filed namespaceField, protocol context.Protocol, entity *supervisor.ObjectEntity)`
where `filed` will be `server` and `pipeline`...

**Comment by zhao-kun** [comment]
What is the X problem we want to solve in the design?

Why do we need the general pipeline, what are the benefits that can bring to us when the general pipeline is introduced?

Could I use the same HTTP-server or Kafka-backend filter in the HTTP pipeline or MQTT Pipeline, aka, we can share the filter between different kinds of Pipeline?

We must get a clear target before we begin to design, I think you should clarify the benefits

**Comment by suchen-sci** [comment]
Thanks a lot for your question. Here are my personal understanding about these questions. Please don't hesitate to tell me if i am wrong or you have better ideas.

1. i think the X problem we want to solve in this design is to create a general pipeline that can be used in all different protocols, like HTTP, MQTT, TCP etc. 
2. Control logic between different protocol pipeline should be similar. By introducing this general pipeline, we can support more protocols easily. And when we add new functions to pipeline, it will benefit all different protocols. 
3. i think we should allow filter sharing between different kinds of pipelines. But we also need to consider the difference among protocols. my naive idea is for every filter, we have general parameters that works for all protocols, and also some parameters that works for only several protocols. For example, Kafka filter, backend is general for all different protocols. but getting topic from HTTP header may only works for http protocol.

**Comment by suchen-sci** [comment]
this design is too naive... i will close this issue.
