### ISSUE TITLE
Is there any way to use Easegress etcd cluster storage api in my own custom business filter?

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#511]
I am developing new filter using Easegress，in other api gateway sometime I need to use cluster cache like redis to cache expired token，but in Easegress it already has etcd embedded and I don't want to introduce new outer cache component， so is it possible to use Easegress own cluster storage api do something like this, or is it a proper way?

**Comment by localvar** [comment]
Please check if the [CustomData](https://github.com/megaease/easegress/pull/500) feature meets your requirement (the PR has been merged, but the feature has not been released yet, please get the latest code from the main branch).
Or, you can use the APIs in the `cluster` package directly for data storage.

**Comment by jthann** [comment]
Thanks, CustomData cannot support expired data store. I investigate the source code，currently the only way to to initialize cluster storage api for client user is to get command opt params and call cluster.New(opt) like the way in cmd/server/main.go.  We should support something like factory pattern in pkg/cluster/cluster_interface.go  so client user can get cluster instance conveniently.

**Comment by samutamm** [comment]
@jthann  You don't have to initialize new cluster instance, because Easegress creates one instance at startup and it's reused everywhere. Here's [example](https://github.com/megaease/easegress/blob/main/pkg/filter/headerlookup/headerlookup.go#L138-L140) how you access to the global cluster instance from `Filter.Init` function.

**Comment by jthann** [comment]
Thanks，I get it.
