### ISSUE TITLE
Reversed proxy for Websocket should support control base on uri

### ISSUE THREAD

**Issue by Oseenix** [megaease/easegress#512]
A backend server listens on a port 3000, serving for both common HTTP requests and WebSocket communication with a special URI (eg. /api/live/ws). Currently, the Websocket proxy does not support control based on a special URI path.

**Describe the solution you'd like**
the WebSocket proxy can support control based on a special URI path.

**Additional context**
Run Grafana behind a reverse proxy:
https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by suchen-sci** [comment]
`WebSocketProxy` has a lot of update in the past year. For more information about it, please check: [here](https://github.com/megaease/easegress/blob/main/doc/cookbook/websocket.md)
