### ISSUE TITLE
The method context.HTTPContext.Request().Scheme() in Easegress always return empty string

### ISSUE THREAD

**Issue by jthann** [megaease/easegress#522]
I am developing custom filter and need to get client url protocol(http or https) using ```context.HTTPContext.Request().Scheme()``` method and it always return empty string ""，the source implementation is using go standard lib api ```http.Request.URL.Scheme```，the counterpart issue is here [https://github.com/golang/go/issues/28940] https://github.com/golang/go/issues/28940. I think we should fix it，I currently parse scheme in my own filter using following way just as reference
```go
func parseScheme(r context.HTTPRequest) string {
	proxyProto := r.Header().Get("X-Forwarded-Proto")
	if proxyProto != "" {		
		return proxyProto
	}
	if r.Std().TLS != nil {
		return "https"
	}
	return "http"
}
```

**Comment by localvar** [comment]
hi @jthann , please help check if #529 fix the issue, thanks.
