### ISSUE TITLE
report ETCD metrics

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#526]
Currently, Easegress only reports metrics of itself, but for some issues, like https://github.com/megaease/easegress/issues/413, the root cause is on the ETCD side, so it would be helpful for troubleshooting if Easegress can also report ETCD metrics.

**Comment by aniaan** [comment]
Does the community have plans to support external etcd? In this way, we can use Alibaba Cloud's etcd, which can reduce operation and maintenance costs, and they can handle the reporting of some metrics

**Comment by xxx7xxxx** [comment]
https://github.com/megaease/easegress/pull/1137 fixed
