### ISSUE TITLE
enable/disable profile at runtime

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#532]
Easegress could generate CPU & memory profiles for troubleshooting, but this feature can only be enabled from the configuration at startup.

However, some issues only happen after Easegress runs for a long time, if profiling is not enabled at first, it will be very hard to reproduce the issue.

So, we need to add new admin APIs to enable/disable profiles at runtime.

**Comment by samutamm** [comment]
This would be very useful for debugging memory or cpu issues! 

I could work on this. The API could be following:

|Path|Method|Description|Data|
|--|--|--|--|
|/profile/|GET|Get info of current CPU & memory profiling. For example, whether enabled and what's the path to file.|-|
|/profile/start/cpu|POST|Start profiling CPU to given file.|Path for CPU profile file.|
|/profile/stop/cpu|POST|Stops profiling and dumps the results to file.|-|
|/profile/start/memory|POST|Start profiling memory to given file.|Path to Memory profile file.|
|/profile/stop/memory|POST|Stop profiling and dumps results to file.|-|

The profiling logic already exists in https://github.com/megaease/easegress/blob/main/pkg/profile/profile.go and the endpoint methods above could use it to start and stop profiling.
