### ISSUE TITLE
Reduce ETCD memory usage when having large number of HTTPPipelines

### ISSUE THREAD

**Issue by samutamm** [megaease/easegress#541]
**Is your feature request related to a problem? Please describe.**
When creating a HTTPServer with 1000 HTTPPipelines, like described in this issue https://github.com/megaease/easegress/issues/413, the Easegress starts increasing memory usage and in few hours it will run out of memory on 16GB machine. This is due the fact that Easegress uses etcd key-value store and [etcd stores 5000 most recent modifications to memory](https://github.com/etcd-io/etcd/blob/29c3b0f307107fd95a6eb43ddff20db952eeb2fa/server/etcdserver/server.go#L75-L80). In most of the use cases this is totally fine, but when there are 1000 httppipelines, each modification stored to etcd is quite large (> 2MB) and having 5000 of them in memory is too much.

**Describe the solution you'd like**
There are multiple ways to reduce the memory consumption:

Let's note the size of a single item stored to etcd by `y`. The total memory consumption (there are probably other factors too) is roughly `5000 * y`

To reduce the memory usage: 
1. Compress data stored to etcd. New compressed data `y' << y` and therefore `5000y' << 5000y`
2. Update some tiny dummy items in etcd for every update of real data. For example, if 10 dummy items is updated for one real data item, the real data items in memory is only `500y` and if dummy items are really small (`~ 0`), the 4500 dummy items stored in memory are `4500 ~ 0 = 0` so total memory usage is about `500y << 5000y`
3. Split the item to smaller individual items. If a item size of `y` is splitted to 1000 (because 1000 pipelines) smaller items of size `y/1000 = y'` and there are still 5000 of these small keys in the memory, the total memory consumption is 1000 times smaller.

What are the advantages and disadvantages of these options?
||Advantage|Disadvantage|branch
|--|--|--|--|
|1|Easy to implement|Needs to decompress when consuming keys and depends whether data is easy to compress |https://github.com/samutamm/easegress/tree/experiment-sync-status-compression|
|2|Easy to implement|Ugly and not correct way to do things. (in quick experience it does not work well) |https://github.com/samutamm/easegress/tree/experiment-add-dummy-etcd-keys|
|3|Clean solution and etcd best practise|Require a bit more refactoring|https://github.com/samutamm/easegress/tree/experiment-smaller-statuses|

![easegress_ram_split_transaction](https://user-images.githubusercontent.com/7460037/157852935-138a2902-b146-48fa-b636-76308a348626.png)

**Describe alternatives you've considered**

**Additional context**

---
Thanks for contributing 🎉!

**Comment by haoel** [comment]
Good investigation, let‘s go to the clean solution ....
