### ISSUE TITLE
`Makefile.build_docker` support custom image name

### ISSUE THREAD

**Issue by aniaan** [megaease/easegress#544]
**Is your feature request related to a problem? Please describe.**

When using easegress, it will involve `secondary development (eg: add custom filters)`, so we need to compile our custom docker image, currently the image name inside `Makefile.build_docker` is `fixed`, I think it is possible to support **custom names by means of variables**

https://github.com/megaease/easegress/blob/0313d7c69d894b8434d2414d4bb8dabf8a309b92/Makefile#L83-L95

**Describe the solution you'd like**

support custom image name, In this way, secondary development can do less magic operations(像主流看齐，永不魔改)
eg:
```
IMAGE_NAME?=megaease/easegress

build_docker:
	cd ${MKFILE_DIR}
	mkdir -p build/cache
	mkdir -p build/bin
	docker run -w /egsrc -u ${shell id -u}:${shell id -g} --rm \
	-v ${GO_PATH}:/gopath -v ${MKFILE_DIR}:/egsrc -v ${MKFILE_DIR}build/cache:/gocache \
	-e GOPROXY=https://goproxy.io,direct -e GOCACHE=/gocache -e GOPATH=/gopath \
	megaease/golang:1.17-alpine make build DOCKER=true
	docker build -t ${IMAGE_NAME}:${RELEASE} -f ./build/package/Dockerfile .
	docker tag ${IMAGE_NAME}:${RELEASE} ${IMAGE_NAME}:latest
	docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:server-sidecar
	docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:easemesh
```

**Describe alternatives you've considered**

**Additional context**

---
Thanks for contributing 🎉!

**Comment by samutamm** [comment]
Thanks for the suggestion ^^ .
I think that if you just want to rename the image, you could do
```bash
make build_docker 
docker tag megaease/easegress:latest somethingelse/easegress:latest
```
and then you can push the renamed image to your registry or run locally etc.. 

I think that renaming/retagging the image is already easy enough.. Or am I missing something?

**Comment by aniaan** [comment]
> 

If the image_name is fixed, then when I do "make builder_docker", the RELEASE I pass in cannot be equal to `v1.6.0`, but to `aniaan-v1.6.0`, so as to avoid conflicts with the official `v1.60`.

If you can support custom image_name, you can pass in the standard version number, and the end result may be `harbor.aniaan.me/easegress:v1.6.0`, which is a bit more convenient.

Of course, the current way works too, but it requires a little extra work

**Comment by samutamm** [comment]
Ok I see, yeah it makes sense.. Can you make this contribution?
