### ISSUE TITLE
404 in docs page

### ISSUE THREAD

**Issue by spongecaptain** [megaease/easegress#550]
There are 404 error in the following websites: 
- https://megaease.com/blog/2021/08/13/the-next-generation-service-gateway/#ease-cookbook
- https://megaease.com/zh/blog/2021/08/13/the-next-generation-service-gateway/#easegress-%E7%A4%BA%E4%BE%8B

it Includes
- Reverse Proxy (Load balancing) — Rich strategies of load balancing [[doc](https://github.com/megaease/easegress/blob/main/doc/cookbook/load_balancer.md)]
- Service Discovery — Zookeeper, Eureka, Consul, Nacos, etc. [[doc](https://github.com/megaease/easegress/blob/main/doc/cookbook/service_proxy.md)]
- API Aggregation — Aggregating many APIs into a single API. [[doc](https://github.com/megaease/easegress/blob/main/doc/cookbook/api_aggregator.md)]
- Distributed Tracing — Supporting APM tracing — Zipkin. [[doc](https://github.com/megaease/easegress/blob/main/doc/cookbook/distributed_tracing.md)]
- Flash Sales. High concurrent promotion sales. [[doc](https://github.com/megaease/easegress/blob/main/doc/cookbook/flash_sale.md)]

May use `_` instead of `-` to rename the markdown file.

**Comment by spongecaptain** [comment]
README file also includes the above markdown file. Renaming file should be careful.

**Comment by haoel** [comment]
Thanks to reporting this issue, we will fix the blog links in our website
