### ISSUE TITLE
Simplify CORSAdaptor

### ISSUE THREAD

**Issue by samutamm** [megaease/easegress#570]
**Is your feature request related to a problem? Please describe.**
https://github.com/megaease/easegress/pull/498 enabled both CORS pre-flight and CORS requests for CORSAdaptor while originally only CORS pre-flight requests were possible. In many cases both CORS pre-flight and CORS requests are necessary and should be enabled by default.

**Describe the solution you'd like**
Either 
- change default value of `supportCORSRequest` to true
- remove `supportCORSRequest` and support both CORS pre-flight and CORS requests by default. 

**Describe alternatives you've considered**

**Additional context**

---
Thanks for contributing 🎉!

**Comment by jxd134** [comment]
I support the second measure.
Users reduce the cost of learning about cross-domain settings.

**Comment by localvar** [comment]
close as #839 resolves this issue.
