### ISSUE TITLE
logger support custom log-format-pattern

### ISSUE THREAD

**Issue by aniaan** [megaease/easegress#576]
## background:

We are currently in the process of connecting easegress to the company's unified logging platform, which currently has two specifications:
1. the format of the log output to file is "json-format"
2. each log must contain two fixed keys, `project` and `@timestamp`, `project` is used to distinguish the project (also used as index in ES)

There are some additional settings.
1. the file name supports a custom pattern, eg: "stdout-${podIp}.log"
2. each log record can support variable parameters

Currently, easegress only supports `console` mode, so if you want to meet the above requirements, you will need to customise the source code.

I'd like to hear your thoughts on the easegress log module

## See:
1. ingress-nginx:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#log-format-upstream

2. logback: https://logback.qos.ch/
```xml
<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>${LOG_PATH}/${APP_NAME}_${ADDRESS}_total.log</file>
    <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
        <jsonGeneratorDecorator class="net.logstash.logback.decorate.FeatureJsonGeneratorDecorator"/>
        <providers>
            <timestamp>
                <timeZone>GMT+8</timeZone>
            </timestamp>
            <pattern>
                <pattern>
                        {"project":"${APP_NAME}","address":"${ADDRESS}","level":"%level","thread":"%thread","traceId":"%X{traceId}","msg":"[%class{36}.%M:%L]%msg","stack_trace":
                        "%exception{10}", "remoteAddr":"%X{remoteAddr}"}
                </pattern>
            </pattern>
        </providers>
    </encoder>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
        <fileNamePattern>${LOG_PATH}/${APP_NAME}_${ADDRESS}_total-%d{yyyy-MM-dd-HH}.txt</fileNamePattern>
        <maxHistory>24</maxHistory>
    </rollingPolicy>
</appender>
```

**Comment by samutamm** [comment]
I wonder if something like this in `pkg/logger/logger.go` would work

```go
func newJsonLogger(opt *option.Options, filename string, maxCacheCount uint32) *zap.SugaredLogger {
	if opt.DisableAccessLog {
		return zap.NewNop().Sugar()
	}

	encoderConfig := zapcore.EncoderConfig{
		TimeKey:       "@timestamp", // TIMESTAMP HERE
		LevelKey:      "",
		NameKey:       "",
		CallerKey:     "",
		MessageKey:    "message",
		StacktraceKey: "",
		LineEnding:    zapcore.DefaultLineEnding,
	}

	fr, err := newLogFile(filepath.Join(opt.AbsLogDir, filename), maxCacheCount)
	if err != nil {
		common.Exit(1, err.Error())
	}

	syncer := zapcore.AddSync(fr)
	encoder := zapcore.NewJSONEncoder(encoderConfig)
	encoder.AddString("project", "FIXED-PROJECT-NAME-HERE")
	core := zapcore.NewCore(encoder, syncer, zap.DebugLevel)

	return zap.New(core).Sugar()
}
```

I am not exactly sure if easegress-server configuration should support adding these (or others) custom keys `@timestamp` and `project`. I think that easegress-server configuration could specify whether logging is either "console" or "json" format.

Then when it comes to fixed keys, easegress-server configuration could expose keys in [zapcore.EncoderConfig](https://github.com/uber-go/zap/blob/v1.21.0/zapcore/encoder.go#L313) and possible fixed key-value pairs.

**Comment by samutamm** [comment]
Here's a draft, how configuring the format and custom keys `@timestamp` and `project` could look like:
```yaml
name: easegress-001
cluster-name: easegress-cluster
cluster-role: primary
cluster:
...
api-addr: 127.0.0.1:2381
data-dir: ./data
...
# replace existing key log-dir by logging
logging:
  path: ./log
  format: json
  time-key: "@timestamp"
  custom-keys:
    key: project
    value: "PROJECT-NAME"
```
@aniaan What do you think? Would  this kind of yaml configuration make sense for you?
