### ISSUE TITLE
`syncStatusToCluster` string pointer reference error

### ISSUE THREAD

**Issue by aniaan** [megaease/easegress#581]
**Describe the bug**

https://github.com/megaease/easegress/blob/75f06b5003534cf93c8ef86223fc4acc25e77c17/pkg/object/statussynccontroller/statussynccontroller.go#L262-L274

`kvs[key] = &value` There is a bug in this line of code

**To Reproduce**

Minimal reproduction case：

```go
func main() {
	n := map[string]string{"a": "1", "b": "2", "c": "3"}
	o := make(map[string]*string)

	// value 0x14000112570=last item
	for k, value := range n {
		o[k] = &value
	}

	// map[a:0x14000112570 b:0x14000112570 c:0x14000112570]
	fmt.Println(o)
	
	// map[a:3 b:3 c:3] because 3 is n last item
	for k, v := range o {
		fmt.Println(k, *v)
	}

}

```

**Expected behavior**
Expected output: map[a:1 b:2 c:3]
Actual output: map[a:3 b:3 c:3]

cc @samutamm

**Comment by samutamm** [comment]
Thanks for reporting this @aniaan .
