### ISSUE TITLE
CI support `golangci-lint`

### ISSUE THREAD

**Issue by aniaan** [megaease/easegress#600]
Some common errors can be reduced by adding linter, eg: #582 

linter-tool: golangci-lint https://golangci-lint.run/

![telegram-cloud-photo-size-5-6296100320392097713-y](https://user-images.githubusercontent.com/40813941/165882408-705b6d13-2012-495c-8f42-0c409dd1299f.jpg)

**Comment by suchen-sci** [comment]
#1068 added it. I have to say, `golangci-lint` is an amazing tool. Thanks a lot for your advice.
