### ISSUE TITLE
support different types of tracer by configuration, such as skywalking, currently only zipkin

### ISSUE THREAD

**Issue by sodaRyCN** [megaease/easegress#698]
We are currently using skywalking instead of zipkin in production environment . We expect to be able to switch to skywalking as easily as modifying the configuration, rather than secondary development on easegress.

**Comment by localvar** [comment]
Thanks for raising the requirement, we will consider adding the support.

**Comment by aniaan** [comment]
Suggest replacing zipkin with opentelemetry

**Comment by aniaan** [comment]
I think the problem has been solved, you can easegress tracing to configure `otlp exporter`, and select `skywalking receiver` in otel collector.

You can refer to the documentation:
1. https://github.com/megaease/easegress/blob/main/doc/cookbook/distributed-tracing.md#exporter
2. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/tracing/otel-collector-config.yml
3. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/skywalkingreceiver

I'll close the issue and we'll discuss it when we have questions.
