### ISSUE TITLE
Tests `TestSemaphoreRobust` and `TestSemaphoreN` failed randomly

### ISSUE THREAD

**Issue by Loyalsoldier** [megaease/easegress#72]
See here: https://github.com/megaease/easegress/pull/68

**Comment by benja-wu** [comment]
Thx for reminding. 
Let me figure out what's wrong here. 
* MacOS go test failed due to the `semaphore_test`
* Ubuntu go test failed due to the `cluster_test`

**Comment by xxx7xxxx** [comment]
Try it multiple times, it will reproduce the failure. The reason here is it gave a too min gap of the time in a limited CPU resource. So the failure will be eliminated by increasing the time gap. 

@qdongxu please check it out.


```bash
$ cd pkg/util/sem
$ GOMAXPROCS=1 go test -v
=== RUN   TestSemaphore0
--- PASS: TestSemaphore0 (0.10s)
=== RUN   TestSemaphoreRobust
--- PASS: TestSemaphoreRobust (1.07s)
=== RUN   TestSemaphoreN
    semaphore_test.go:153: time too long: 211.624608ms, sem: 799, trans: 800
--- FAIL: TestSemaphoreN (2.33s)
FAIL
exit status 1
FAIL    github.com/megaease/easegress/pkg/util/sem      3.624s
```

**Comment by qdongxu** [comment]
We implemented a Semaphore strategy when there's not an 'official` semaphore.  Now we can employ https://pkg.go.dev/golang.org/x/sync/semaphore, then less unit test is required.
