### ISSUE TITLE
possible regression introduce by FaaSController 

### ISSUE THREAD

**Issue by tg123** [megaease/easegress#73]
lines below are removed in #59

```
ci = &cacheItem{ipFilterChan: path.ipFilterChain, path: path}
rules.putCacheItem(ctx, ci)
m.handleRequestWithCache(rules, ctx, ci)
return
```

https://github.com/megaease/easegress/commit/d6af0dc2667660fc836dfa49923dba54ea8dea13#diff-9a718d32cef26863af1d2292e908365d40b9d2f761b2bc1bbde6ec743d3b8bdd

when you run the example in readme
https://github.com/megaease/easegress#create-an-httpserver-and-pipeline
you will always get 404 because of `path.Headers === nil`

the egress server will never touch any backend server if no header set in config object

**Comment by xxx7xxxx** [comment]
Yes, we have fixed that problem, will merge it in the next PR. Thx

**Comment by benja-wu** [comment]
@tg123 Thanks
In the original PR, I notice the `mux` package has a potential problem for handling requests even in the header-not-match scenario. So I remove it and create a discussion related to it. 
For a stable usage scenario, please use the `1.0.0` tag version's Easegress, and I will open a new issue for this not feature-related modification next time. 
 
BTW: the correct logic here should be `if there are headers related setting, not match will cause a 404, else it is a path matching. We will fix it in the next PR.

**Comment by benja-wu** [comment]
@tg123 We had launched the fixing PR #76, and in normal path-matching(Readme example) and header-matching(FaaSController) scenarios, Easegress can work as expected. 

Thanks for reporting this bug again. :-)
