### ISSUE TITLE
The questions issue template is not available.

### ISSUE THREAD

**Issue by grootpiano** [megaease/easegress#745]
**Describe the bug**
The `questions.yaml` template in `.github/ISSUE_TEMPLATE` directory is not available. We need a none blank `title`.

**Additional context**
According to [this article](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#key-must-be-a-string):
> Empty strings, or strings consisting of only whitespaces, are not permissible when the field expects a string.

**Comment by grootpiano** [comment]
Fix it, or delete it, that is the question.

**Comment by localvar** [comment]
thanks for reporting this, we will fix it.
