### ISSUE TITLE
Integration with Linkerd

### ISSUE THREAD

**Issue by madugula007** [megaease/easegress#767]
**Is your feature request related to a problem? Please describe.**
Can easegress be integrated with Linkerd

**Describe the solution you'd like**
I would like to use Linkerd,  as it has lesser latency than other service meshes. But features like circuit break etc. are not available in Linkerd. Easegress anyhow helps in having those features..

---
Thanks for contributing 🎉!

**Comment by localvar** [comment]
hi @madugula007 , I'm unclear about the word `integration` and your requirement.
For service mesh, we have a product [EaseMesh](https://github.com/megaease/easemesh) built on Easegress.

**Comment by madugula007** [comment]
EaseMesh is limited to javaspring cloud ... My APIs are in Golang. Also no mTLS as of now..

**Comment by xxx7xxxx** [comment]
EaseMesh also supports other languages besides Java/Spring by installing [EaseMesh-CoreDNS](https://github.com/megaease/easemesh/blob/main/docs/install.md#install-coredns) .

And actually, we have supported mTLS[1] now without updating the document, which will be done soon.

[1] https://github.com/megaease/easegress/blob/38eac8e335ece1cb3494c1f2033c017cf999338b/pkg/object/meshcontroller/spec/spec.go#L120

**Comment by haoel** [comment]
> EaseMesh is limited to java spring cloud ... My APIs are in Golang. Also no mTLS as of now..

EaseMesh supports other languages. we have the demo for golang application, you can have look - https://github.com/megaease/easemesh-demo

**Comment by xxx7xxxx** [comment]
@madugula007  I've added a demo guide in README for https://github.com/megaease/easemesh-demo , please check it out.

**Comment by madugula007** [comment]
Thank you will certainly try. 
Kindly help me if I stuck somewhere.
Will update..
