### ISSUE TITLE
Add data builder

### ISSUE THREAD

**Issue by caoshengdong** [megaease/easegress#803]
Add a data builder to support data transformation from one stage to another. 

DataBuilder is used to manipulate and store data. The data from the previous filter can be transformed and stored in the context so that the data can be used in subsequent filters.

### Configuration

| Name            | Type   | Description                                   | Required |
|-----------------|--------|-----------------------------------------------|----------|
| template        | string | template to create data, please refer the [template](https://github.com/megaease/easegress/blob/main/doc/reference/filters.md#template-of-builder-filters) for more information        | Yes       |
| dataKey         | string | key to store data        | Yes       |
| leftDelim       | string | left action delimiter of the template, default is `{{`  | No       |
| rightDelim      | string | right action delimiter of the template, default is `}}` | No       |

### Results

| Value                                                                       | Description                                        |
| --------------------------------------------------------------------------- | -------------------------------------------------- |
| buildErr                                                                    | Error happens when build the result.               |

**Comment by localvar** [comment]
I've updated the `template` filed to be **required**.
