### ISSUE TITLE
adjust minimal log level at runtime

### ISSUE THREAD

**Issue by localvar** [megaease/easegress#855]
the minimal log level is currently statically configured via the configuration.
this means, when we meet an issue and need to change to the minimal log level to get more information from the log, we will have to shut down easegress and restart.
however, some issues cannot be reproduced after a restart.
so it would be a help if we could adjust the minimal log level at runtime.

**Comment by aniaan** [comment]
Consider adding `LoggerController(SystemController)`, which listens to `log events` to change the `log level` , this relationship is like the relationship between `RawConfigTrafficController` and `Pipeline`

https://github.com/uber-go/zap/issues/556

**Comment by xxx7xxxx** [comment]
Fixed by https://github.com/megaease/easegress/pull/1133
