### ISSUE TITLE
[Question]:  How do I access the easegress cluster

### ISSUE THREAD

**Issue by wj-stack** [megaease/easegress#925]
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

easegress can be deployed as a cluster, but front-end access can access only one node in the cluster. If this node fails, the front-end does not know about the other nodes. Is there a good solution? Or do we need to add another?

**Comment by suchen-sci** [comment]
Hi, thanks a lot for your question. 

We think your frontend should not access easegress node directly anyway. If your frontend only access one easegress node, then other unused nodes are kind of waste of resources (although they can see as data backup). 

And for your question, a solution is add a load balance layer in front of easegress, which know all easegress nodes, and your frontend app access this load balance layer. So you can use all easegress nodes. And if one fail, you can use other. For example, you can share your domain name with multiple servers.

Can this solution help you solve your problem?

**Comment by wj-stack** [comment]
> Hi, thanks a lot for your question.
> 
> We think your frontend should not access easegress node directly anyway. If your frontend only access one easegress node, then other unused nodes are kind of waste of resources (although they can see as data backup).
> 
> And for your question, a solution is add a load balance layer in front of easegress, which know all easegress nodes, and your frontend app access this load balance layer. So you can use all easegress nodes. And if one fail, you can use other. For example, you can share your domain name with multiple servers.
> 
> Can this solution help you solve your problem?

Yes, DNS can solve this problem, thank you
