### ISSUE TITLE
[Question]: filters doc doesn't include GRPCProxy

### ISSUE THREAD

**Issue by hhhcj** [megaease/easegress#953]
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

Filter `GRPCProxy` isn't included in filter docs. Author could write this for grpc is a popular protocol over the world. I found this feature by making a global search in the code.

**Comment by sodaRyCN** [comment]
Thanks for your reminder.
 I will write and submit the filter doc as soon as possible after the [PR](https://github.com/megaease/easegress/pull/977) is merged.

**Comment by sodaRyCN** [comment]
[PR](https://github.com/megaease/easegress/pull/1000)，doc is submitted.
